# Configuration file for Experimental Drivetrain

# PhotonVision Configuration
#shooter
camera.0.name=monochrome_camera_0
photonvision.robot_to_camera_0.x_meters=0.293
photonvision.robot_to_camera_0.y_meters=-0.108
photonvision.robot_to_camera_0.z_meters=0.295
photonvision.robot_to_camera_0.roll_degrees=1.0
photonvision.robot_to_camera_0.pitch_degrees=-24.1
photonvision.robot_to_camera_0.yaw_degrees=1

#hopper
camera.1.name=monochrome_camera_1
photonvision.robot_to_camera_1.x_meters=-0.048
photonvision.robot_to_camera_1.y_meters=0.326
photonvision.robot_to_camera_1.z_meters=0.5398
photonvision.robot_to_camera_1.roll_degrees=2.8
photonvision.robot_to_camera_1.pitch_degrees=-6
photonvision.robot_to_camera_1.yaw_degrees=135

#left
camera.2.name=color_camera_2
photonvision.robot_to_camera_2.x_meters=-0.333
photonvision.robot_to_camera_2.y_meters=-0.323
photonvision.robot_to_camera_2.z_meters=0.536
photonvision.robot_to_camera_2.roll_degrees=0.6
photonvision.robot_to_camera_2.pitch_degrees=20.1
photonvision.robot_to_camera_2.yaw_degrees=186

#right
camera.3.name=color_camera_3
photonvision.robot_to_camera_3.x_meters=-0.333
photonvision.robot_to_camera_3.y_meters=0.323
photonvision.robot_to_camera_3.z_meters=0.536
photonvision.robot_to_camera_3.roll_degrees=-0.3
photonvision.robot_to_camera_3.pitch_degrees=20
photonvision.robot_to_camera_3.yaw_degrees=174

photonvision.max_ambiguity=0.3
photonvision.max_z_error=0.75
photonvision.linear_std_dev_baseline=0.02
photonvision.angular_std_dev_baseline=0.06
photonvision.camera0_std_dev_factor=1.0
photonvision.camera1_std_dev_factor=1.0
photonvision.linear_std_dev_multitag_factor=0.5
photonvision.angular_std_dev_multitag_factor=Infinity

# Tuner Constants Configuration
tuner.steer_kp=100.0
tuner.steer_ki=0.0
tuner.steer_kd=0.5
tuner.steer_ks=0.1
tuner.steer_kv=2.49
tuner.steer_ka=0.0
tuner.drive_kp=1.54
tuner.drive_ki=0.0
tuner.drive_kd=0.0
tuner.drive_ks=0.25086
tuner.drive_kv=0.11691
tuner.drive_ka=0.010278
tuner.slip_current_amps=100.0
tuner.stator_current_limit_amps=60.0
tuner.speed_at_12_volts_meters_per_sec=5.85
tuner.drive_canbus_name=TRex
tuner.couple_ratio=3.375
tuner.drive_gear_ratio=6.03
tuner.steer_gear_ratio=26.09090909090909
tuner.wheel_radius_inches=2.0
tuner.pigeon_id=6

tuner.mech_canbus_name=null

# Encoder Offsets (in rotations)
tuner.front_left_encoder_offset_rotations=-0.019775390625
tuner.front_right_encoder_offset_rotations=0.474609375
tuner.back_left_encoder_offset_rotations=0.18432617875
tuner.back_right_encoder_offset_rotations=-0.15478515625

# Motor IDs
tuner.front_left_drive_motor_id=21
tuner.front_left_steer_motor_id=20
tuner.front_left_encoder_id=2
tuner.front_right_drive_motor_id=23
tuner.front_right_steer_motor_id=22
tuner.front_right_encoder_id=3
tuner.back_left_drive_motor_id=27
tuner.back_left_steer_motor_id=26
tuner.back_left_encoder_id=5
tuner.back_right_drive_motor_id=25
tuner.back_right_steer_motor_id=24
tuner.back_right_encoder_id=4

# Inverted
tuner.front_left_steer_motor_inverted=false
tuner.front_left_steer_encoder_inverted=false
tuner.front_right_steer_motor_inverted=false
tuner.front_right_steer_encoder_inverted=false
tuner.back_left_steer_motor_inverted=false
tuner.back_left_steer_encoder_inverted=false
tuner.back_right_steer_motor_inverted=false
tuner.back_right_steer_encoder_inverted=false

# Module Positions (in inches)
tuner.front_left_pos.x_inches=10.875
tuner.front_left_pos.y_inches=10.875
tuner.front_right_pos.x_inches=10.875
tuner.front_right_pos.y_inches=-10.875
tuner.back_left_pos.x_inches=-10.875
tuner.back_left_pos.y_inches=10.875
tuner.back_right_pos.x_inches=-10.875
tuner.back_right_pos.y_inches=-10.875

container.joystick_scale_factor= 0.95

# Mechanisms

# Hood
mech.hood_retracted_degrees=77
mech.hood_min_angle_degrees=57
mech.hood_gear_ratio=1.33
#24/18
# 2.25
# shaft revs per mech rev: 164.0/10.0=16.4
mech.hood_shaft_revs_per_mech_rev=16.4

#Intake
mech.robot_to_intake_yaw_degrees=180