# Configuration file for Hulk

# PhotonVision Configuration
camera.0.name=monochrome_camera_0
photonvision.robot_to_camera_0.x_meters=-0.0315
photonvision.robot_to_camera_0.y_meters=-0.3595
photonvision.robot_to_camera_0.z_meters=0.534
photonvision.robot_to_camera_0.roll_degrees=2.1
photonvision.robot_to_camera_0.pitch_degrees=12.7
photonvision.robot_to_camera_0.yaw_degrees=270

camera.1.name=monochrome_camera_3
photonvision.robot_to_camera_1.x_meters=0.0215
photonvision.robot_to_camera_1.y_meters=0.3375
photonvision.robot_to_camera_1.z_meters=0.049
photonvision.robot_to_camera_1.roll_degrees=2.8
photonvision.robot_to_camera_1.pitch_degrees=-6.5
photonvision.robot_to_camera_1.yaw_degrees=90

photonvision.max_ambiguity=0.3
photonvision.max_z_error=0.75
photonvision.linear_std_dev_baseline=0.02
photonvision.angular_std_dev_baseline=0.06
photonvision.camera0_std_dev_factor=1.0
photonvision.camera1_std_dev_factor=1.0
photonvision.linear_std_dev_multitag_factor=0.5
photonvision.angular_std_dev_multitag_factor=Infinity

# Tuner Constants Configuration
tuner.steer_kp=100.0
tuner.steer_ki=0.0
tuner.steer_kd=0.5
tuner.steer_ks=0.1
tuner.steer_kv=1.59
tuner.steer_ka=0.0
tuner.drive_kp=0.8
tuner.drive_ki=0.0
tuner.drive_kd=0.0
tuner.drive_ks=0.0
tuner.drive_kv=0.124
tuner.slip_current_amps=120.0
tuner.stator_current_limit_amps=60.0
tuner.speed_at_12_volts_meters_per_sec=4.73
tuner.drive_canbus_name=null
tuner.couple_ratio=3.5714285714285716
tuner.drive_gear_ratio=6.746031746031747
tuner.steer_gear_ratio=12.8
tuner.wheel_radius_inches=2.0
tuner.pigeon_id=6

tuner.mech_canbus_name=null

# Encoder Offsets (in rotations)
tuner.front_left_encoder_offset_rotations=0.178955078125
tuner.front_right_encoder_offset_rotations=0.211181640625
tuner.back_left_encoder_offset_rotations=0.16650390625
tuner.back_right_encoder_offset_rotations=-0.107177734375

# Motor IDs
tuner.front_left_drive_motor_id=21
tuner.front_left_steer_motor_id=20
tuner.front_left_encoder_id=2
tuner.front_right_drive_motor_id=23
tuner.front_right_steer_motor_id=22
tuner.front_right_encoder_id=3
tuner.back_left_drive_motor_id=27
tuner.back_left_steer_motor_id=26
tuner.back_left_encoder_id=5
tuner.back_right_drive_motor_id=25
tuner.back_right_steer_motor_id=24
tuner.back_right_encoder_id=4

# Inverted
tuner.front_left_steer_motor_inverted=false
tuner.front_left_steer_encoder_inverted=false
tuner.front_right_steer_motor_inverted=false
tuner.front_right_steer_encoder_inverted=false
tuner.back_left_steer_motor_inverted=false
tuner.back_left_steer_encoder_inverted=false
tuner.back_right_steer_motor_inverted=false
tuner.back_right_steer_encoder_inverted=false

# Module Positions (in inches)
tuner.front_left_pos.x_inches=9.75
tuner.front_left_pos.y_inches=9.75
tuner.front_right_pos.x_inches=9.75
tuner.front_right_pos.y_inches=-9.75
tuner.back_left_pos.x_inches=-9.75
tuner.back_left_pos.y_inches=9.75
tuner.back_right_pos.x_inches=-9.75
tuner.back_right_pos.y_inches=-9.75

container.joystick_scale_factor=1

# Mechanisms

# Hood
mech.hood_retracted_degrees=83
mech.hood_min_angle_degrees=43
mech.hood_gear_ratio=2.25
# shaft revs per mech rev: 164.0/10.0=16.4
mech.hood_shaft_revs_per_mech_rev=16.4

#Intake
mech.robot_to_intake_yaw_degrees=-90